# Generated by Django 3.2.4 on 2021-06-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='movie.Genre'),
        ),
        migrations.RemoveField(
            model_name='multik',
            name='genre',
        ),
        migrations.AddField(
            model_name='multik',
            name='genre',
            field=models.ManyToManyField(related_name='multik', to='movie.Genre'),
        ),
    ]
